const lec_names = [
'4|kidney,suprarenal gland & ureter,bladder and ureth|1|',
'5|kidney,suprarenal gland & ureter,bladder and urethra|1|',
'6|Anatomy of Thyroid and Parathyroid glands|1|',
'7|female reproductive organs & external genitalia|1|',
'8|Kidney & suprarenal gland, ureter, posterior abdominal wall and urinary bladder & urethra|1|',
'9|Muscles of the pelvis and perinium, the perieal region, pelvic floor and fossae|1|',
'10|muscles, fascia & peritonium of the pelvis perineum, the perineal region and fossae|1|',
'11|surface anatomy and surgical incisions in GUS|1|',
'12|The anatomy of anaesthesia for episiotomy during labour Anatomy; anatomy of urinary incontinence and prolapsed|1|',
'13|the bony pelvis(male and female)|1|',
'14|the inguinal region, male reproductive organs & male external genitalis|1|',
'15|What is the clinical anatomy of the bony pelvis in relation to labour|1|',
'16|Introduction to the biochemistry of hormones and their mechanism of hormone action 1|25|',
'17|Introduction to the biochemistry of hormones and their mechanism of hormone action 2|25|',
'18|Blood sugar examination|26|',
'19|Urine sample testing and interpretation(dipstick),Advising patient how to collect midstream urine and preg test|26|',
'20|Dietary modifications advised for patients with chronic kidney disease, nephrotic syndrome and urinary stone disease|27|',
'21|AIDS|27|',
'22|Prevention of Diabetes Mellitus|27|',
'23|Public health screening in obs.and gyn|27|',
'24|Risk Factors for Diabetes Mellitus|27|',
'25|The epidemiology and prevention of the major sexually transmitted infections including HIV|27|',
'26|Development of the Endocrine system and Congenital Abnormalities|28|',
'27|Development of the male and female genital systems with clinical correlates|28|',
'28|development of urinary system and clinical correlate|28|',
'29|Formation and histology of the placenta, extraembryonic membrane and twin|28|',
'30|Gametogenesis|28|',
'31|Genetics in pregnancy, screening|28|',
'32|Ovulation and fertilization|28|',
'33|Antenatal care and screening in pregnancy|29|',
'34|Abnormal menstrual bleeding|30|',
'35|Abnormal vaginal bleeding during first trimester|30|',
'36|Assisted reproductive technology ART|30|',
'37|Exam Gyne|30|',
'38|Exam Obst|30|',
'39|Female catheterization|30|',
'40|Hist Gyne|30|',
'41|History in Obs|30|',
'42|Infertility (male and female)|30|',
'43|Speculum examination|30|',
'44|Histological structure of male gental tract|31|',
'45|Histological structure of nephron and blood circulation in kidney|31|',
'46|Histological structure of ovaries, ducts, uterus, cervix, vagina and external genitalia (female genital tract)|31|',
'47|Histological structure of the kidney, ureter and urinary bladder|31|',
'48|Histology of Endocrine system|31|',
'49|Histology of GUS|31|',
'50|Histology of mammery gland|31|',
'51|Professionalism 1|32|',
'52|Professionalism 2|32|',
'53|History in GUE / CP 1|33|',
'54|Insulin therapy|33|',
'55|Intrduction to GUS module|33|',
'56|Physical Exam in GUE / CP 2|33|',
'57|Polyuria and polydipsia|33|',
'58|. E. coli , Klebsiella, Proteus & Enterobacter spp|34|',
'59|Common microrganism of reproductive system|34|',
'60|IgA nephropathy and Post streptococcus glomerulonephritis|34|',
'61|Immunological aspect of infertility|34|',
'62|Microbiology of GUS|34|',
'63|Microorgansims that cross the placenta|34|',
'64|Retroviruses AIDS|34|',
'65|Schistosoma haematobium|34|',
'66|Sexual transmited diseases|34|',
'67|Staphylococcus saprophyticus and Enterococcus|34|',
'68|Trichomonas Vaginalis|34|',
'69|﻿Immunology of endocrine system|34|',
'70|Case studies of acute and chronic renal failure.|35|',
'71|benign tumers and malignancy of the breast|2|',
'72|Ccommon diseases of reproductive system|2|',
'73|﻿Diseases Affecting Tubules and Interstitium, Renal Stones, and Cystic Diseases of Kidney|2|',
'74|Diseases of testis and prostate.|2|',
'75|Diseases of the ovaries|2|',
'76|Diseases of the placenta|2|',
'77|Diseases of the uterus|2|',
'78|Diseases of the vulva, vagina and cervix|2|',
'79|Glomerular diseases|2|',
'80|Kidney Tumors and Diseases of urinary bladder|2|',
'81|Non neoplastic diseases of the breast|2|',
'82|Non neoplastic diseases of thyroid gland|2|',
'83|Pathology of Adrenal Gland|2|',
'84|Pathology of Adrenal Gland & ﻿non neoplastic and neoplastic diseases of thyroid gland|2|',
'85|Thyroid malignancy and Parathyroid Pathology|2|',
'86|Tubulointerstitial nephritis, cystic diseases of kidney|2|',
'87|Drug prescription in GUS|36|',
'88|Drugs acting on the uterus|36|',
'89|Drugs affecting male reproductive system|36|',
'90|Drugs used to treat Thyroid diseases|36|',
'91|Treatment of HIV|36|',
'92|Corticosteroid drugs|36|',
'93|Diuretics|36|',
'94|Drugs for infertility & assisted reproduction|36|',
'95|Drugs used to treat Diabetes mellitus|36|',
'96|Female sex hormones & contraception|36|',
'97|Treatment of sexually transmitted diseases|36|',
'98|Treatment of UTI|36|',
'99|A Functional Overview of Endocrine System : Hormone Receptors|37|',
'100|Acid Base Balance by The Kidney.|37|',
'101|Kidney regulation of sodium and water balance|37|',
'102|Mechanism of errection and ejaculation|37|',
'103|Physiology of Normal Menstrual cycle.|37|',
'104|Physiology of Pancreas (Insulin and Glucagon)|37|',
'105|Physiology of The Adrenal Glands|37|',
'106|Physiology of Thyroid and Parathroid Glands|37|',
'107|Pitutary Function and Control Pitutary Hormones. Hypothalamic Hormones|37|',
'108|The Endocrine Role of Placenta and Maintenance of Pregnancy, lactation and menopause|37|',
'109|Urine Formation (Filtration, Absorption and Secretion).|37|',
'110|Water and Electrolyte Balance by The Kidney.|37|',
'111|Radiological imaging techniques of the genitourinary tract,|38|',
'112|radiology in obs, and gynecology|38|',
'113|Imaging of the breast|38|',
'114|Stem cell|39|',
'115|Breast lump|40|',
'116|Breast examination|40|',
'117|Central neck mass and change in weight|40|',
'118|Evaluation of a patient presenting with hematuria|41|',
'119|Evaluation of a patient presenting with lower urinary tract symptoms|41|',
'120|History in GUE / CP 1|41|',
'121|Male catheterization|41|',
'122|Physical Exam in GUE / CP 2|41|',
];
